### ISSUE TITLE
Whats next for development?

### ISSUE THREAD

**Issue by tindli** [marko-js/marko-widgets#105]
Issue to sum up all relevant topics for Marko and Marko-Widgets regarding further development/improvements.

The points listed here are coming from various discussions... and are not be be seen as a roadmap.
It is kind of a collection for ideas.

1. Having each component serializing its own state on the server side is not perfect. (payload on html size etc...) It would be better to have an intelligent object store that keeps references even when serialized, de-serialized. That way, data only needs to be send down to the client as a single source and can be converted back into its original structure easily. This topic is considered to be "nice to have" but definitely an improvement.

**Comment by mlrawlings** [comment]
Fixed in #151
