### ISSUE TITLE
Scoped packages break client runtime

### ISSUE THREAD

**Issue by tropperstyle** [marko-js/marko-widgets#114]
I have a widget in a standalone repository. It has a `marko-taglib.json`, a renderer, and a `widget.js` file for `w-bind`

Everything works as long as the package name does not contain a scope. If it contains a scope, the following error is thrown in the browser at run time:

Error: Cannot find module "/$/@scope/package-name/widget" from "/$/marko-widgets/lib"

**Comment by patrick-steele-idem** [comment]
Ok. That does look like a bug. I'll need to investigate to see what needs to change to support scoped packages. Thanks for opening the issue.

**Comment by patrick-steele-idem** [comment]
Fixed in raptor-modules: https://github.com/raptorjs/raptor-modules/issues/15

Please let me know how things go after a fresh npm install and also deleting the `.cache/` directory in the root of your project. Please confirm if this fixes your problem so that I can close the issue. Thanks!

**Comment by tropperstyle** [comment]
Hmm I cleared out `node_modules` and `.cache`, confirmed `raptor-modules@1.2.0` was installed upon refresh, but I am still running into that same error.

**Comment by patrick-steele-idem** [comment]
Let me see if I can reproduce. I just focused on adding unit tests to support scoped packages, but I have not tested in a real app.

**Comment by patrick-steele-idem** [comment]
Hey @tropperstyle, I was able to reproduce in a real app. I'm investigating the issue. Thanks for your patience.

**Comment by patrick-steele-idem** [comment]
@tropperstyle I found the issue. I should have a fix soon.

**Comment by patrick-steele-idem** [comment]
Hey @tropperstyle. An additional fix was required: https://github.com/raptorjs/raptor-modules/commit/958ce4658688e95c1c858bf6a4617323b134fe84

I tested locally in a real app and was able to reproduce and things are working as expected with the latest version of `raptor-modules`: `raptor-modules@1.2.1` 

Please test again with a fresh npm install and after deleting the `.cache/` directory. Please let me know if this resolves your problem. Thanks!

**Comment by tropperstyle** [comment]
Problem resolved. Much appreciated!

**Comment by patrick-steele-idem** [comment]
Great. Thanks again.
