### ISSUE TITLE
Allow for w-preserve-attrs to enable preservation of attributes

### ISSUE THREAD

**Issue by 1N50MN14** [marko-js/marko-widgets#121]
`w-preserve-attrs="style,class"` 

Because Marko Widgets doesn't maintain a separate virtual DOM it will reset manual changes to element attributes on `rerender()` . It should be possible to specify attributes for Marko to ignore. This is mostly the case with `class` and `style` attributes where external animation / tweening engines such as Velocity.js or GSAP are often used whereas we still wish to rely on `setState()` while still maintaining element styles as set manually outside Marko.

**Comment by patrick-steele-idem** [comment]
New version published: `marko-widgets@5.3.0`
