### ISSUE TITLE
this.$() breaks when passing an attribute selector with '#' in it

### ISSUE THREAD

**Issue by merwan7** [marko-js/marko-widgets#128]
In Marko Widgets, if I use something like this:

```javascript
this.$('[href="#jumpLink"]')
```

I get no results.  The reason is because the `idRegExp` regular expression used in [lib/Widget.js](https://github.com/marko-js/marko-widgets/blob/master/lib/Widget.js) is matching it as an ID.

Since Javascript regular expressions don't support negative look-behind, I suggest using an expression like this one `/([^="'])?\#(\w+)( .*)?/` And adjusting a couple of things in the selection logic.

**Comment by patrick-steele-idem** [comment]
Thanks for the fix @merwan7 !. New version published: `marko-widgets@5.3.5`

I did make one small tweak to not use a capturing group: https://github.com/marko-js/marko-widgets/commit/ea7b0bdaa506be93c87099b23f779596ccb9d410
