### ISSUE TITLE
Widget should skip DOM update if the widget is destroyed before update occurs

### ISSUE THREAD

**Issue by avigy** [marko-js/marko-widgets#137]
A number of times we see morphedDom exception because of state changes that trigger a dom refresh on the widget after a widget is destroyed. This usually happens with unit tests. We usually get around this by setting Timeout before calling done(). But this solution is not scalable. We need to add a better check to not try re-rendering the DOM after it is destroyed.

**Comment by patrick-steele-idem** [comment]
This has been fixed and new versions published:

- `marko-widgets@6.1.1`
- `marko-widgets@5.3.6`
