### ISSUE TITLE
"Cannot find module" error

### ISSUE THREAD

**Issue by tbashor** [marko-js/marko-widgets#139]
Got the error:

`"Uncaught Error: Cannot find module "/project$1.0.0/plugins/components/sc-controller/index.js" from "/$/marko-widgets/lib"`

Tried deleting the cache and verifed that sc-controller/index.js was included in browser.json for the page. I could see that sc-controller/index.js was included in the page, but it could not be properly referenced. 

With help from @patrick-steele-idem, the root cause was having multiple versions of lasso in the project. Once the versions were synced, the error went away and the page behaved correctly.

**Comment by patrick-steele-idem** [comment]
Doing some cleanup.
