### ISSUE TITLE
Proposal: Template as entry point for UI components

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko-widgets#167]
# Current setup:
### `index.js`

``` javascript
module.exports = require('marko-widgets').defineComponent({
    template: require('./template.marko'),
    getTemplateData: function(state) { ... },
    ...
});
```
### `template.marko`

``` xml
<div w-bind>
    ...
</div>
```
# Proposed solution

The above setup is not bad, but there is some boilerplate that we would like to remove by making the following changes:
- Rename: `index.js` → `component.js`
- Rename: `template.marko` → `index.marko` (the template becomes the entry point)
- Remove: `require('marko-widgets').defineComponent(...)`
- Remove: `template: require('./template.marko')`

Marko Widgets will detect that the template is the entry point and compile the template differently such that it no longer exports a `Template` instance, but rather it will be a module that exports two methods:
- `render(input)` - Allows the UI component be rendered via a JavaScript API (e.g., `require('my-component').render({ name: 'Frank' }).appendTo(document.body);`)
- `renderer(input, out)` - Used by the custom tag renderer

The previous setup would now be simplified as shown below:
### `component.js`

``` javascript
module.exports = {
    getTemplateData: function(state) { ... },
    ...
};
```
### `index.marko`

``` xml
<div w-bind>
    ...
</div>
```
# Additional thoughts
## Future improvements

By making the template the entry point, we can do a lot more things that were not previously possible. This is because we have full control over how a Marko template is compiled while we don't have control how the user writes the JavaScript code. 
## Single file component

We could easily support inlining the JavaScript code for the component into the template as shown below:

``` html
<div w-bind>
    ...
</div>

<script marko-component>
var Component = {
    getTemplateData: function(state) { ... },
    ...
};
</script>
```
## No references to `marko-widgets`

With the new setup, there are no references to the `marko-widgets` module when building a UI component. This is a good thing since it makes it easier to merge Marko Widgets functionality into the core `marko` package (future proposal).
## Backwards compatibility

We intend to maintain backwards compatibility. Developers could start to use the new, simplified setup, but old code would continue to work.
## Related proposals
- [Issue #152 - Proposal: Marko Widgets with ES6 and inline Marko templates](https://github.com/marko-js/marko-widgets/issues/152)

**Comment by yomed** [comment]
Would there be any proposed changes to `defineRenderer` and `defineWidget` in this case? Are you looking to phase those out?

**Comment by patrick-steele-idem** [comment]
@yomed 

> Would there be any proposed changes to defineRenderer and defineWidget in this case? Are you looking to phase those out?

To keep things simple I didn't want to go into the split renderer case, but we would also like to simplify that as well by removing the calls to `defineRenderer` and `defineWidget`:

# Split widget/renderer

## `src/components/my-component/`

### `renderer.js`

```javascript
module.exports = {
    getTemplateData: function(state) { ... },
    ...
};
```

### `widget.js`

```javascript
module.exports = {
    handleFooClick: function() { ... },
    ...
};
```

### `index.marko`

```xml
<div w-bind>
    ...
</div>
```

**Comment by philidem** [comment]
I would very much look forward to this change.

**Comment by basickarl** [comment]
Ah, this looks amazing!

Also:
```
module.exports = {
    getTemplateData: function(state) { ... },
    ...
};
```
Not?:
```
export default {
    getTemplateData: function(state) { ... },
    ...
};
```

**Comment by patrick-steele-idem** [comment]
@basickarl You are free to use ES6 (you'll need to use babel on both the server and the browser if you use `import`/`export` though). We plan on allowing the following as well:

```javascript
export default class {
    handleFooClick() { ... }
    handleBarClick() { ... }    
    ...
};
```

The only good reason to use `class` is that you don't have to worry about comma separators, which is kind of nice.

**Comment by patrick-steele-idem** [comment]
Closing this issue in favor of the issue created on the `marko` repo: https://github.com/marko-js/marko/issues/416
