### ISSUE TITLE
Declarative DOM event listeners broken for non-bubbling events on repeated elements

### ISSUE THREAD

**Issue by smulder** [marko-js/marko-widgets#170]
In Marko 3.12.1 and Marko-Widgets 6.4.1 looped elements with custom event handlers in a template are getting assigned the same id and in some cases only firing the event on the first element in the group.

A temporary workaround for me has been assigning the status variable on the for loop as follows:

<div for(img in data.images | status-var=loop) id="imageHolder${loop.getIndex()" w-onMouseOver="handleSomething"></div>

**Comment by patrick-steele-idem** [comment]
New version published with fix: `marko-widgets@6.6.0`
