### ISSUE TITLE
Calling A component in  for loop . only trigering first element 

### ISSUE THREAD

**Issue by anupnitkkr** [marko-js/marko-widgets#174]
<for(filterlist in filter.arr)>
                <listing-filter-checkbox  filterlist=filterlist w-onClick ="afterCheckBoxAction" /> 
            </for>

-----------  listing-filter-checkbox ---------

<div w-bind>
<li w-onClick ="checkFilterCheck" data-name="${data.filterlist.name || data.filter.name}" data-key = "${data.filterlist.key}">
    <input type="checkbox" class="filled-in" ${data.checked ? 'checked' : ''}/>
    <label>
        <i class="smart-pay"></i><span>${data.filterlist.name}</span>
    </label> 
</li> 
</div>

**Comment by anupnitkkr** [comment]
/Users/anup.kumar1/Documents/webapp/node_modules/marko/compiler/Compiler.js:126
            throw error;
            ^

Error: An error occurred while trying to compile template at path "/Users/anup.kumar1/Documents/webapp/girf/components/listing-filter-checkbox/template.marko". Error(s) in template:
1) [girf/components/listing-filter-checkbox/template.marko:2:0] Unable to handle event ""click"". HTML element is not nested within a widget.

**Comment by anupdineout** [comment]
closing this

**Comment by shanimal** [comment]
I solved this specific error by adding `w-bind` to the root element of my template.
