### ISSUE TITLE
Provide public method to initialize widgets with given IDs

### ISSUE THREAD

**Issue by philidem** [marko-js/marko-widgets#26]
Currently, the method of initializing widgets with given IDs is done via a private method that is put into the `window` object:
```javascript
window.$rwidgets = function(ids)
```

We should expose this method as part of the public interface:
```javascript
window.$rwidgets = exports.initWidgets = function(ids)
```

See `marko-widgets-browser.js`

This addresses the inability to write your own JavaScript code to dynamically initialize the widgets that were rendered to an HTML fragment on the server-side when using `eval()` is not an option.

**Comment by philidem** [comment]
Also, see #25 which should be fixed along with this issue.

**Comment by patrick-steele-idem** [comment]
Fixed by https://github.com/marko-js/marko-widgets/commit/eba73f8dabf68e05388297fa6152e875c958293a
