### ISSUE TITLE
defineRenderer ends the output stream

### ISSUE THREAD

**Issue by jackhorton** [marko-js/marko-widgets#53]
When our renderer.js looks like the following:
```javascript
module.exports = require('marko-widgets').defineRenderer({
    // ...
});
```
It will correctly render the given component but then end the output stream. However, when we use the following:
```javascript
exports.render = function render(input, out) {
    // ...
    template.render(data, out);
};
```
The output stream remains open and further components can be rendered. Is this the intended behavior?

**Comment by patrick-steele-idem** [comment]
Hi @jackhorton, there is no code in `defineRenderer` that ends the output stream. Internally, `defineRenderer` just calls `template.render(data, out)`. The problem may be more specific to how your code is structured. Can you please share more details?

**Comment by patrick-steele-idem** [comment]
Hi @jackhorton, can you please provide more details to reproduce the issue? Thanks.

**Comment by patrick-steele-idem** [comment]
I'm doing some house cleaning... If this is still an issue please reopen. Thanks.
