### ISSUE TITLE
Reused stateful widget constructor event listening can lead to EventEmitter leak

### ISSUE THREAD

**Issue by philidem** [marko-js/marko-widgets#60]
In a stateful widget, it might be necessary to listen to the destroy event. In most cases you register a `destroy` listener in the constructor.

For example:
```javascript
init: function() {
    this.on('destroy', function(event) {
        // do something
    });
}
```

Every time the widget is re-rendered, this triggers the `init` function to be called for the same widget.
If widget is repeatedly re-rendered due to state change, this error will be triggered:
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```

This is a _workaround_ but I'm not really happy with it:
```javascript
init: function() {
    if (!this._initialized) {
        this._initialized = true;
        this.on('destroy', function() {
            // do something
        });
    }
}
```

Wanted to see if there's a cleaner way to write code that should be only ran the first time the widget is created.

**Comment by patrick-steele-idem** [comment]
What are your thoughts on adding support for an `initOnce()` method? The `initOnce()` method would only be called once while the `init()` method would be called every time a widget is updated.

**Comment by tindli** [comment]
personally, I would love to see a initOnce() method! I have a few things were I need the workaround @philidem mentioned.

**Comment by philidem** [comment]
I'm wondering if `destroy` event should fire when the widget is being re-rendered (even if it is reusing the old widget). I think we need to do a little work to make this less confusing. I personally find it strange that `init` for a single widget will be called multiple times.

If we're not going to emit `destroy` event when re-rendering then we might want to support:
- `init` called during _first_ construction
- `onUpdate` called _after_ each update due to re-rendering

So if you need to handle any DOM changes after re-rendering then maybe `onUpdate` would be the right place to do that (not in the one-time constructor `init` function).

**Comment by tindli** [comment]
@philidem good question... I am not even sure about when the destroy event fires... (never used it so far...) I would assume that it fires when the DOM behind the component will be removed... so re-rendering the widget should not fire the destroy event...

For your specific case couldn't you just use the onDestroy() method for widgets??? Although it does not seem to be documented, it is mentioned in our FAQ. (https://github.com/marko-js/marko-widgets/blob/master/docs/faq.md#which-component-functions-are-invoked-at-what-time---whats-the-order-of-invocation)

**Comment by philidem** [comment]
The reason that I think that `destroy`/`onDestroy` should happen during re-render _based on current design_ is because it would mirror when `init` (the constructor-like function) is called. If the widget went through the destroy lifecycle event then the listener subscriptions would be removed (and that would have solved my original problem).

However, I still think that neither `init` or `destroy` should happen during re-render. I think if the end-user wants to handle DOM changes due to re-render then they should do that in `onAfterUpdate`.

So hopefully I can convince you all to change the design so that `init` is not called during re-render :) I know that might be breaking change but I think it would be worth it.

**Comment by philidem** [comment]
It looks like the main problem that I was seeing as far as destroy not being called was actually due to installing `raptor-dom` at the root of my project.

**The hairy details:**
`raptor-dom` and `marko-widgets` both need to use the same `raptor-pubsub`. When `raptor-dom` was installed as root module in my project, it didn't find `raptor-pubsub` because my project did not have `raptor-pubsub` installed and neither did `raptor-dom`. When you install `marko-widgets` it will also include `raptor-pubsub` as the dependency and this is the one that you want `marko-widgets` and `raptor-dom` to share.

**Workaround:**
use `require('marko-widgets/dom')` to access the `raptor-dom` module from your project and don't install `raptor-dom` into your project as a top-level dependency.


I'm going to close this issue for now and let's revisit the init/destroy flows in the future.

**Comment by patrick-steele-idem** [comment]
It seems reasonable to make `init()` only be called once for the entire life of the widget. I think it is definitely something we should consider for the next major version of marko-widgets.

Regarding `raptor-pubsub`, I am surprised you are seeing issues since `raptor-pubsub` creates a global variable for that very reason:
https://github.com/raptorjs/raptor-pubsub/blob/419231e0b88ee6201ae21d4519f76d256af42dae/lib/index.js#L3

**Comment by yomed** [comment]
Just chiming in a +1 for some implementation of `initOnce()`. I've run into usecases where I re-render part of a widget very often and would prefer some separation of the the actual initialization versus updating.

**Comment by hliang93** [comment]
I'm trying to use the workaround in [the first post](https://github.com/marko-js/marko-widgets/issues/60#issue-97079117) but it seems like `this._initialized` reverts back to `undefined` during every init, so the condition is always satisfied.

Does this workaround still work in marko v5, or can `initOnce()` be used now?

**Comment by patrick-steele-idem** [comment]
Hey @hliang93, with the Marko v5 release we changed the behavior:

- The `init()` constructor for a widget is only called once even if a widget is rerendered

Please see:
https://github.com/marko-js/marko-widgets/blob/master/CHANGELOG.md#breaking-changes 

Therefore, the workaround to prevent the constructor being invoked multiple times should not be necessary. Are you seeing a widget constructor being invoked multiple times?

**Comment by hliang93** [comment]
I see it being invoked twice.

I am currently trying to make D3 charts out of components in Marko. For my line chart, I have a component called `data-series` whose template looks like this:
```
<g w-bind>
    <line-path path="$data.path" />
</g>
```
In `init()`, the component creates a SVG path out of some fake data and then sets the state:
```
this.setState({
            'path': path,
...
```
The SVG path is then passed to the line-path widget through `getTemplateData`:
```
   getTemplateData: function(state) {
        return {
            path: state.path
        }
    },
```
The `line-path` widget takes the `path` prop and inserts it into the template to render a SVG path (this is the 'line' of the line chart):
```
getTemplateData: function(state, input) {
        console.log(input);
        return {
            path: input.path
        }
    },
```
`  <path d=${data.path} class="line" />`

However, the line does not show up when I use `setState` to set the path property, and `init` appears to run twice. The line shows up properly if I do the path-genertion inside `getTemplateData` instead of using `setState`.

**Comment by patrick-steele-idem** [comment]
Hey @hliang93, would you be able to setup a minimal project for reproducing the issue? It could be a bug, but we do have tests to make sure the `init()` function is only invoked once.

**Comment by hliang93** [comment]
Sure! I'm also at eBay Orchard, so maybe I could ping you later. :-)

**Comment by hliang93** [comment]
Here is the repo, I hope it is minimal enough: https://github.com/hliang93/marko-d3

I had used one of the Marko samples ("widget communication") as my initial seed.

**Comment by anupdineout** [comment]
Same Issue is happening with me also
