### ISSUE TITLE
notEmpty not working for Boolean flags?

### ISSUE THREAD

**Issue by neolegolas14** [marko-js/marko-widgets#64]
@patrick-steele-idem 

I am not sure why this is specifically not working for me but notEmpty(data.something.booleanFlag) is not working and returning false all the time.

```
<if test="notEmpty(out.global.isMobile)">
</if>
```
isMobile is the boolean flag

**Comment by neolegolas14** [comment]
Answer:

we will never have to check if a boolean is not empty as even if it is empty usage will return false

**Comment by patrick-steele-idem** [comment]
For reference, here is the implementation of the `notEmpty()` helper: https://github.com/marko-js/marko/blob/36ba6763fd3a1e0b1ff978c732d7a6c15a3dc621/runtime/helpers.js#L20-L30

Docs need to be improved and better describe the builtin `empty()` and `notEmpty()` helpers. We have an open Github issue for this: https://github.com/marko-js/marko/issues/15
