### ISSUE TITLE
namespace internal widget methods

### ISSUE THREAD

**Issue by yomed** [marko-js/marko-widgets#76]
I recently attempted to call one of my widget methods `update`, which didn't work. I dug into the source a bit and saw that `update` is one of the many internal methods that are setup on each widget (`Widget.js`).  Maybe it would be better to namespace "private" methods like this that are only meant to accessed by marko-widgets.  This would free up those names to be used by developers.

**Comment by patrick-steele-idem** [comment]
`update()` should be documented, but it was not necessarily meant to be private. Most widgets will not override this method or call it directly, but that is something that is allowed. Calling `update()` will force the DOM to update immediately. Normally updates are queued up. You could in theory do the following:

```javascript
this.setState('foo', 'bar');
this.update();
this.setState('hello', 'world');
this.update();
```

I'm open to the idea of making it private for v5 and switching to `_update()`, but I am leaning more towards just making `update()` a public method with documentation. Thoughts?

**Comment by yomed** [comment]
I agree, with `update()` specifically, it might make more sense to just make it public. I think there are a handful of methods that are undocumented and also not namespaced, like: update, doUpdate, isDirty, getBodyEl, and maybe others. I guess it wasn't clear to me if these were intentionally undocumented because they're private, or just undocumented. Happy to help clean these up.

**Comment by patrick-steele-idem** [comment]
@yomed interested in sending a PR to document those special methods? If you aren't sure of the proper description for any of those methods I can always go back and update. Any help is greatly appreciated!

**Comment by yomed** [comment]
Sounds good, will do!
