### ISSUE TITLE
implement standard event bubbling methods for use with declarative bindings

### ISSUE THREAD

**Issue by yomed** [marko-js/marko-widgets#97]
For the custom event delegation that is implemented in declarative bindings, we should support standard methods related to event bubbling, such as:
```
event.stopPropagation()
event.stopImmediatePropagation()
```

There are also older properties like `event.cancelBubble` which we probably don't need to worry about.

**Comment by patrick-steele-idem** [comment]
New version published with `event.stopPropagation()` support: `marko-widgets@5.2.3`

Thank you, @1N50MN14, for the PR!
